-- ============================================================
-- Crivox Schema (Reference Only)
-- 
-- For fresh setup: Run migrations in order:
--   1. migrations/001_initial_schema.sql
--   2. migrations/002_add_user_memory.sql
--   3. migrations/003_update_profile_trigger.sql
--
-- For existing database: Just run migration 002 and 003
-- ============================================================

-- This file kept for reference. Use migrations folder for all schema changes.